name: add-date-tag
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: mydea/action-tag-date-version@v20
    - run: deploy-app
