name: add-date-tag
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: git tag %DATE:~10,4%.%DATE:~7,2%.%DATE:~4,2%
      shell: cmd
    - run: git push --tags
      shell: cmd
